/**
 * Malzeme Görsel Prompt Üretici — Seed Verileri
 */

import { IngredientStyleProfile, IngredientItem } from "../../types/ingredient";

const now = Date.now();

// Varsayılan stil profili
export const defaultStyleProfiles: Omit<IngredientStyleProfile, "id">[] = [
  {
    name: "Sade Minimal",
    cameraAngle: "45-degree overhead angle, slightly tilted to show depth",
    lighting: "Soft natural daylight from a left-side window, gentle shadows",
    surface: "Clean white marble surface with subtle veining",
    colorPalette: "Warm pastels, cream, soft gold accents, muted earth tones",
    atmosphere: "Minimal, clean, professional artisan kitchen feel",
    framing: "Close-up with breathing space around the subject, shallow depth of field",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Pralet Cesur",
    cameraAngle: "Straight-on eye level, product dead-center, symmetrical framing",
    lighting: "Soft commercial studio lighting, single key light from 45-degree top-left, 5500K neutral daylight, low-contrast 2:1 key-to-fill ratio, gentle graduated shadows",
    surface: "Flat, vivid red #B5102C solid background, no texture, no gradient",
    colorPalette: "Dominant vivid red #B5102C (75%), clean white accents, deep black #1A1A1A touches, warm temperature 2700-3500K",
    atmosphere: "Bold, playful, contemporary, clean digital aesthetic with zero grain or texture, energetic and appetizing",
    framing: "Product fills approximately 40% of frame height, centered, isolated by shallow depth of field against flat graphic background",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Sade Editorial",
    cameraAngle: "Slightly elevated 30-degree angle, centered composition with generous negative space",
    lighting: "Soft warm studio lighting with subtle shadow beneath subject, gentle dimensionality without harshness",
    surface: "Soft warm beige/cream gradient background with subtle texture, minimalist and calm",
    colorPalette: "Warm neutrals — cream, beige, golden brown, natural food colors as accents, premium and accessible",
    atmosphere: "Artisanal, sophisticated, approachable luxury, editorial restraint, homemade quality with professional presentation",
    framing: "Product in upper-middle area with ample breathing room, generous white space surrounding",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Ramen Enerjik",
    cameraAngle: "Overhead butterfly angle, flat depth, all elements in sharp focus",
    lighting: "Overhead butterfly studio light at 5500K daylight neutral, soft diffused quality, 2:1 low-contrast key-to-fill ratio, minimal soft shadow beneath subject",
    surface: "Warm sand beige #D9C9B8 with subtle wave pattern texture at 8% opacity, paper-like warmth",
    colorPalette: "Warm sand beige #D9C9B8 (60%), crimson red #C8281A accents (20%), clean whites (15%), natural studio whites on food products",
    atmosphere: "High-energy, festive, bold, contemporary 2020s digital style, cultural authenticity, commercial food photography energy",
    framing: "Product fills 55% of frame width, slightly elevated on clean studio surface, no harsh shadows",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Yarim Tabak Temiz",
    cameraAngle: "Top-left 45-degree natural window light angle, asymmetric rule-of-thirds",
    lighting: "Top-left 45-degree natural window light, soft diffused quality, 5500K daylight neutral, 4:1 key-to-fill ratio, soft shadows falling to lower-right",
    surface: "Neutral off-white #F0EFED surface, slight warmth in highlights, clean and uncluttered",
    colorPalette: "Monochromatic — off-white #F0EFED (50%), burnt sienna #C8631A accents (35%), deep brown #1A1008 touches (5%), muted saturation",
    atmosphere: "Energetic, fresh, contemporary, no texture overlay, flat depth of field, inviting and modern",
    framing: "Product in center-left quadrant, fills 45% of frame height, moderate negative space, asymmetric but balanced",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

// Varsayılan malzemeler
export const defaultIngredientItems: Omit<IngredientItem, "id">[] = [
  {
    name: "Mascarpone",
    description: "Her gün Sade imalathanesinde taze üretilir",
    message: "Her gün Sade imalathanesinde taze üretilir",
    usedInProducts: ["Tiramisu", "Cheesecake", "Mascarpone Krema"],
    isActive: true,
    sortOrder: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Meyve Confitleri",
    description: "Mevsim meyvelerinden, Sade mutfağında pişirilir",
    message: "Mevsim meyvelerinden, Sade mutfağında pişirilir",
    usedInProducts: ["Meyve Tartı", "Cheesecake", "Panna Cotta"],
    isActive: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Ganaj Çeşitleri",
    description: "Günlük taze çikolata ile her sabah hazırlanır",
    message: "Günlük taze çikolata ile her sabah hazırlanır",
    usedInProducts: ["Çikolatalı Pasta", "Truffle", "Ekler"],
    isActive: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Tart Hamurları",
    description: "Tereyağı ile Sade fırınında günlük üretim",
    message: "Tereyağı ile Sade fırınında günlük üretim",
    usedInProducts: ["Meyve Tartı", "Karamel Tart", "Quiche"],
    isActive: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Fındık Praline",
    description: "%100 fındık ile Sade üretimidir",
    message: "%100 fındık ile Sade üretimidir",
    usedInProducts: ["Paris-Brest", "Praline Pasta", "Fındıklı Kurabiye"],
    isActive: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Tiramisu Keki",
    description: "İtalyan tarifle Sade imalathanesinde pişirilir",
    message: "İtalyan tarifle Sade imalathanesinde pişirilir",
    usedInProducts: ["Tiramisu"],
    isActive: true,
    sortOrder: 5,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Pesto Sosu",
    description: "Taze fesleğen ile Sade mutfağında hazırlanır",
    message: "Taze fesleğen ile Sade mutfağında hazırlanır",
    usedInProducts: ["Sandviç", "Focaccia", "Salata"],
    isActive: true,
    sortOrder: 6,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Lutenitza Sosu",
    description: "Közlenmiş sebzelerden Sade üretimi",
    message: "Közlenmiş sebzelerden Sade üretimi",
    usedInProducts: ["Sandviç", "Kahvaltı Tabağı"],
    isActive: true,
    sortOrder: 7,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Pasta Kreması",
    description: "Tüm kremalar Sade imalathanesinde günlük üretilir",
    message: "Tüm kremalar Sade imalathanesinde günlük üretilir",
    usedInProducts: ["Ekler", "Millefeuille", "Profiterol", "Pasta"],
    isActive: true,
    sortOrder: 8,
    createdAt: now,
    updatedAt: now,
  },
  {
    name: "Tereyağlı Karamel",
    description: "Gerçek tereyağı ile küçük kazanlarda pişirilir",
    message: "Gerçek tereyağı ile küçük kazanlarda pişirilir",
    usedInProducts: ["Karamel Tart", "Millefeuille", "Karamelli Mousse"],
    isActive: true,
    sortOrder: 9,
    createdAt: now,
    updatedAt: now,
  },
];
